---

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"

- name: Include release specific variables
  include_vars: "{{ ansible_distribution_release }}.yml"
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- include: CentOS.yml
  when: ansible_distribution == "CentOS"

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- include: Debian.yml
  when: ansible_distribution == "Debian"

- name: Ensure that config directory is exists
  file: state=directory path="{{ iptables_confdir }}"
