---

- name: Prepare ip6tables rules
  template:
    src: rules.v6.j2
    dest: "{{ip6tables_rules_path}}"
    owner: root
    group: root
    mode: 0600
  register: ipv6rules
  notify:
    - Restart Iptables Rules
