---

- include_tasks: common_iptables.yml
  when: iptables_enabled or ip6tables_enabled
  tags:
    - iptables

- include_tasks: iptables.yml
  when: iptables_enabled
  tags:
    - iptables

- include_tasks: ip6tables.yml
  when: ip6tables_enabled
  tags:
    - iptables
