---

- include: common_iptables.yml
  when: iptables_enabled or ip6tables_enabled
  tags:
    - iptables

- include: iptables.yml
  when: iptables_enabled
  tags:
    - iptables

- include: ip6tables.yml
  when: ip6tables_enabled
  tags:
    - iptables
