---
# tasks file for iptables (Ubuntu specific)

- name: Install iptables packages (Ubuntu specific)
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 86400
  with_items:
    - "{{ iptables_packages }}"
  notify:
    - Enable and Start Iptables
