---

- name: Enable and Start Iptables
  service:
    name: "{{ iptables_service_name }}"
    state: started
    enabled: yes
  tags:
    - iptables

- name: Restart Iptables
  service:
    name: "{{ iptables_service_name }}"
    state: restarted
  tags:
    - iptables
